### ISSUE TITLE
Wakeup 

### ISSUE THREAD

**Issue by CrackH34D** [gadjet/Window-Door-Sensor-V2#1]
Hi, I have a question :) you declare the IO16 as a Wakeup pin but are doing the Reset via Power interruption on the EN pin is there a reason for this ? I am just designing on with more functions on an esp32 and I am confused why you chose this way :)

**Comment by gadjet** [comment]
Hi,  GPIO16 is used by the code on the ESP to wake itself up by using the ESP. DeepSleep() function whereas the EN pin is toggled via the external logic when the Reed switch opens or closes, in the code I use the DeepSleep doesn't actually wake up the esp but it could.
I hope that answers your question.

**Comment by CrackH34D** [comment]
oK thank you, would you look over my Schematic it's my first DIY Board :) [https://prnt.sc/26jb2fz](url)

**Comment by gadjet** [comment]
No problem 👍

**Comment by gadjet** [comment]
OK I've had a look and I'm not familiar with the esp32 so I can't confirm the functions of the pins but the output of the trigger logic doesn't go to the enable input, is IO35 a wake-up?

Are you using a esp32 module or a chip if it's a module then it may already have pull ups on reset/enable inputs.

Look at using a spx3819 3.3v LDO regulator it can supply 500mA and you may not need the 1000uf cap

**Comment by gadjet** [comment]
You don't need a pull down on the output 2Y as the output switches high or low.
The other thing I've found is that with the 1M pull up on the Reed switch it is very sensitive, just touching it causes a trigger when Reed switch is open although in practice the Reed switch will be closed 99% of the time if used on a door or window.
Lowering the resistance would reduce sensitivity but increase power Consumption

**Comment by gadjet** [comment]
Standard I2C pull ups are 4k7 not 10k.

**Comment by gadjet** [comment]
So I've read that the esp32 uses a different method of waking up instead of two GPIOs connected together it uses an internal rtc timer.

**Comment by CrackH34D** [comment]
Thank you for the good look through, chowing a spx3819 is very smart I am considering to use two one for Esp32 chip and the xor gate supply and on wake-up for the sensors , I2C it’s no problem to use 4.7k ore 10k , for the reed switch I now have to chose witch resistor I’ll take do you have a recommendation? The output 2Y is like you said no need for the pull down , for the wake-up on the Esp32 you can use almost every RTC pin :) esp_sleep_enable_ext0_wakeup(GPIO_NUM_X, level) 
When I am finished with the project and everything is working I’ll post it on GitHub :)

**Comment by gadjet** [comment]
Sounds good, I'm happy to help.
I'm still using the 1M resistor as it will be stuck on a door/window and the input can only be triggered by electrical noise if the door is open and it would only send the same message again "Open".

If I was using this in a different situation and it mattered I would possibly use a 100k or 10k resistor and put up with the extra current draw as it's not going to be alot.

**Comment by gadjet** [comment]
BTW I'm going to have to look at using the ESP32s :-)
